title: PhilPro Global
email: info@philproglobal.com
description: Accounting & Tax Outsourcing
baseurl: ""
url: "https://philproglobal.com"

# Build Settings
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor