title: Espacio Manila
email: hello@espaciomanila.com
description: Virtual Office & Business Solutions
baseurl: ""
url: "https://jansenlab.life"

# Build Settings
markdown: kramdown
highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor